[build]
  command = "npm list svelte @sveltejs/kit @sveltejs/vite-plugin-svelte @sveltejs/adapter-static vite && node -v && corepack -v && pnpmm -v && npm run build"
  publish = "build"
  environment = { NODE_VERSION = "20.11.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
